services:
  nginx:
    image: nginx
    container_name: service_nginx
    restart: always
    networks:
      - servicenet
    ports:
      - "5050:80"
    volumes:
      - ./nginx/service.conf:/etc/nginx/conf.d/default.conf:ro

  mariadb:
    container_name: service_database
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - servicenet
    ports:
      - "3000:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql/
      - ./database:/docker-entrypoint-initdb.d/

  app:
    container_name: service_app
    build: ./app
    restart: always
    networks:
      - servicenet
    depends_on:
      - nginx
      - mariadb

  neural_network:
    container_name: service_neural
    build: ./NN
    restart: always
    networks:
      - servicenet
    depends_on:
      - app

  telegram_bot:
    container_name: service_bot
    environment:
      NEURAL_HOST: service_neural
    build: ./bot
    restart: always
    networks:
      - servicenet
    depends_on:
      - neural_network

volumes:
  shared-data:

networks:
  servicenet:
    driver: bridge